#for AW8680X SENSOR Driver
oplus_bsp_senser_aw86802-y += aw8680x.o
oplus_bsp_senser_aw86802-y += aw_bin_parse.o
oplus_bsp_senser_aw86802-y += aw_soc_protocol_interface.o
oplus_bsp_senser_aw86802-y += aw_com_protocol.o
oplus_bsp_senser_aw86802-y += aw_protocol_fun.o
oplus_bsp_senser_aw86802-y += aw_protocol_map.o
obj-$(CONFIG_AW8680X_SENSOR) += oplus_bsp_senser_aw86802.o
